name: "Rachel Nabors, award-winning cartoonist turned digital storyteller."
description: "Where I post musings about web development, comics, and the future of online interaction."

url: "http://rachelnabors.com"

markdown: kramdown
permalink: pretty
highlighter: pygments

lsi: false

# Default date format is "ordinal" (resulting in "July
date_format: "ordinal"

# Disqus Comments
disqus_short_name: rachelnabors
disqus_show_comment_count: true

# Locations
destination: _site

# Don't flip out whenever I compile my sass
exclude: [_scss]

collections:
- events
#   comics:
#     output: true
#   animations:
#     output: true
#     permalink: /animations/:path/
- projects
- publications

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      sidebar_open: true
  -
    scope:
      path: "" # all files have the `default` layout
      type: "posts"
    values:
      layout: "post"
  # -
  #   scope:
  #     path: "comics"
  #   values:
  #     layout: "comic"
  #     interactive: false
  #     animated: false